### ISSUE TITLE
@conda-forge-admin, please rerender

### ISSUE THREAD

**Issue by zklaus** [conda-forge/openml-feedstock#4]

**Comment by BastianZim** [comment]
Hi @zklaus anything specific that we missed? Please feel free to add you as well, by the way, if you are interested.

**Comment by zklaus** [comment]
Hi @BastianZim, sorry, I should have explained. I have started tackling our backlog of [errored version updates](https://conda-forge.org/status/#version). The openml migrator is the one with the most failed attempts, so I started investigating here. As a consequence of the bot problems, we have missed the last five versions here, where I hope that the most recent one will also address Numpy 2 compatibility.

I think I have tracked down the issue now, so if it's ok for you, I'd like to ask you *not* to perform version updates manually now and to see if I can unstick the bot.

PS: The issue with the metadata should be resolved with https://github.com/regro/cf-graph-countyfair/pull/32.

**Comment by BastianZim** [comment]
Ahh no worries, just wanted to see where the error is. :)

Thank you! Standing by until I get the green light from you.

**Comment by zklaus** [comment]
Alright, the bot is officially unstuck: #6. Seems like openml is not Numpy 2 compatible, so you'll need to add an upper pin.

Feel free to close #5; it is not needed anymore, but I can't do it because the bot opened it and I am not a maintainer.

**Comment by BastianZim** [comment]
Thank you very much for your help here! Done and done, let's see if it goes through.
